# Generated by Django 2.2.10 on 2020-03-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='potential_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Potential Income'),
        ),
    ]
