# Generated by Django 2.2.10 on 2020-03-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200306_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcandidate',
            name='cv_date_shared',
            field=models.DateField(blank=True, null=True),
        ),
    ]
