# Generated by Django 2.2.10 on 2020-03-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200306_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcandidate',
            name='tentative_date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
