# Generated by Django 2.2.10 on 2020-03-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200306_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='consultant',
        ),
    ]
