# Generated by Django 2.2.10 on 2020-03-09 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0009_remove_job_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcandidate',
            name='associate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='as_associate', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
