# Generated by Django 2.2.10 on 2020-03-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20200311_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_default',
        ),
        migrations.AddField(
            model_name='status',
            name='should_create_pipeline',
            field=models.BooleanField(default=False, verbose_name='should create pipeline if selected'),
        ),
    ]
