# Generated by Django 2.2.10 on 2020-03-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20200312_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
