# Generated by Django 2.2.10 on 2020-03-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20200312_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcandidate',
            name='actual_income',
        ),
    ]
