# Generated by Django 2.2.10 on 2020-03-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20200315_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Job Board'},
        ),
    ]
