# Generated by Django 2.2.10 on 2020-03-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20200315_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-date', 'job_candidate']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date', '-reference_number'], 'permissions': [('view_report_jobs_summary', 'Can view report Jobs Summary')]},
        ),
        migrations.AlterModelOptions(
            name='jobcandidate',
            options={'ordering': ['-registration_date', 'job', 'candidate__name']},
        ),
    ]
