# Generated by Django 2.2.10 on 2020-03-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20200316_1505'),
        ('jobs', '0018_auto_20200317_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcandidate',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_consultant', to='contacts.Employee'),
        ),
    ]
