# Generated by Django 2.2.10 on 2020-03-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_interview_done_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcandidate',
            name='cv_source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
