# Generated by Django 2.2.10 on 2020-03-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_jobcandidate_cv_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='board',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
