# Generated by Django 2.2.10 on 2020-03-26 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_auto_20200326_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcandidate',
            name='associate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_associate', to='contacts.Employee'),
        ),
    ]
