# Generated by Django 2.2.10 on 2020-03-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_auto_20200326_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcandidate',
            options={'ordering': ['-registration_date', 'job', 'candidate__name'], 'permissions': [('view_all_job_candidates', 'Can view all Job Candidates')]},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('probability', 'name'), 'verbose_name': 'Job Candidate Status'},
        ),
    ]
