# Generated by Django 2.2.10 on 2020-03-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_auto_20200328_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobstatus',
            options={'ordering': ('order',), 'verbose_name_plural': 'Job Status'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('probability', 'name'), 'verbose_name': 'Job Candidate Status', 'verbose_name_plural': 'Job Candidate Status'},
        ),
    ]
