# Generated by Django 2.2.10 on 2020-04-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_auto_20200405_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-date_time', 'job_candidate']},
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='date',
            new_name='date_time',
        ),
    ]
