# Generated by Django 2.2.10 on 2020-04-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_auto_20200406_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date', '-reference_number'], 'permissions': [('view_report_jobs_summary', 'Can view report Jobs Summary'), ('view_report_job_to_pipeline_analysis', 'Can view report Job to Pipeline Analysis'), ('view_report_interviews', 'Can view report Interviews'), ('can_edit_closed_job', 'Can edit closed Job')]},
        ),
    ]
