# Generated by Django 2.2.10 on 2020-04-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0031_auto_20200408_0117'),
        ('jobs', '0036_historicaljob_historicaljobcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.Employee'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.Employee'),
        ),
    ]
