# Generated by Django 2.2.10 on 2020-04-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_auto_20200408_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljob',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
    ]
