# Generated by Django 2.2.10 on 2020-04-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_historicalinterview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='reference_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Job Reference Number'),
        ),
        migrations.AlterField(
            model_name='job',
            name='reference_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Job Reference Number'),
        ),
    ]
