# Generated by Django 2.2.10 on 2020-04-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_auto_20200411_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcandidate',
            options={'ordering': ['-registration_date', 'job', 'candidate__name'], 'permissions': [('view_all_job_candidates', 'Can view all Job Candidates'), ('view_report_cv_sent', 'Can view report CV Sent to clients'), ('view_start_date_per_week_month', 'Can view Report on Start date per week/month')]},
        ),
    ]
