# Generated by Django 2.2.10 on 2020-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_auto_20200415_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='number_of_positions',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_positions',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
