# Generated by Django 2.2.10 on 2020-05-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_auto_20200511_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='actual_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='actual_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
