# Generated by Django 2.2.10 on 2020-07-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0049_auto_20200710_0556'),
        ('jobs', '0046_auto_20200511_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_recruiters',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Employee'),
        ),
    ]
