# Generated by Django 2.2.10 on 2020-08-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0047_job_assigned_recruiters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assigned_recruiters',
            field=models.ManyToManyField(blank=True, to='contacts.Employee'),
        ),
    ]
