# Generated by Django 2.2.10 on 2020-03-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_employee_commission_role'),
        ('salespipes', '0001_initial'),
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='contacts.Employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='commissions.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_commissions', to='contacts.Employee')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='salespipes.Pipeline')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_commissions', to='commissions.Role')),
            ],
        ),
    ]
