# Generated by Django 2.2.10 on 2020-03-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commission_employeerole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='role',
        ),
        migrations.DeleteModel(
            name='EmployeeRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
