# Generated by Django 2.2.10 on 2020-03-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_auto_20200311_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commission',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commission',
            name='rate_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='role_type',
            field=models.CharField(choices=[('one', 'Level One'), ('two', 'Level Two'), ('three', 'Level Three'), ('others', 'Others')], max_length=100, null=True, unique=True),
        ),
    ]
