# Generated by Django 2.2.10 on 2020-03-12 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_auto_20200311_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_commissions', to='contacts.Employee'),
        ),
    ]
