# Generated by Django 2.2.10 on 2020-03-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_auto_20200312_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratedetail',
            options={'ordering': ('base_minimum', 'base_maximum')},
        ),
    ]
