# Generated by Django 2.2.10 on 2020-03-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_auto_20200318_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
