# Generated by Django 2.2.10 on 2020-03-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_commission_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ('-date', '-pipeline__job_candidate__job__reference_number', 'rate_role_type'), 'permissions': [('view_report_commissions_earned_summary', 'Can view report Commissions Earned Summary'), ('view_all_commissions', 'Can view all commission records')]},
        ),
    ]
