# Generated by Django 2.2.10 on 2020-03-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_interviewmode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visastatus',
            options={'verbose_name_plural': 'Visa Status'},
        ),
    ]
