# Generated by Django 2.2.10 on 2020-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20200313_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=2),
        ),
    ]
