# Generated by Django 2.2.10 on 2020-03-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_setting_display_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='display_date_format',
            field=models.CharField(choices=[('d M Y', '01 Jan 2020'), ('d F Y', '01 January 2020'), ('M d, Y', 'Jan 01, 2020'), ('F d, Y', 'January 01, 2020')], default='d M Y', max_length=50),
        ),
    ]
