# Generated by Django 2.2.10 on 2020-03-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_industry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ('name',), 'verbose_name_plural': 'Industries'},
        ),
    ]
