# Generated by Django 2.2.10 on 2020-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20200330_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='app_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
