# Generated by Django 2.2.10 on 2020-04-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_setting_app_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='app_label',
            new_name='project_label',
        ),
    ]
