# Generated by Django 2.2.10 on 2020-04-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20200403_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='cv_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
