# Generated by Django 2.2.10 on 2020-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_setting_cv_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='cv_label',
            field=models.CharField(default='CV', max_length=50),
        ),
    ]
