# Generated by Django 2.2.10 on 2020-03-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_auto_20200325_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'get_latest_by': '-modified', 'ordering': ('-modified', '-created'), 'permissions': [('download_backups', 'Can download backups')]},
        ),
    ]
