# Generated by Django 2.2.10 on 2020-03-06 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0003_auto_20200305_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.TextField(blank=True, max_length=32)),
                ('alternate_contact_number', models.CharField(blank=True, max_length=32)),
                ('whatsapp_link', models.URLField(blank=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('skype_id', models.CharField(blank=True, max_length=50)),
                ('ms_teams_id', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('commission_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='commissions.Role')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
