# Generated by Django 2.2.10 on 2020-03-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='commission_role',
        ),
    ]
