# Generated by Django 2.2.10 on 2020-03-11 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_employee_commission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
