# Generated by Django 2.2.10 on 2020-03-11 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20200311_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.Employee'),
        ),
    ]
