# Generated by Django 2.2.10 on 2020-03-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20200319_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bls_acls_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dataflow_last_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='haad_dha_license_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_medical',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_title_on_dha_haad',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='candidate',
            name='medical_experience_in_years',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='specialization',
            field=models.TextField(blank=True, verbose_name='Field of specialization'),
        ),
    ]
