# Generated by Django 2.2.10 on 2020-03-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20200321_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='driving_license',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
