# Generated by Django 2.2.10 on 2020-03-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20200322_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_template',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
