# Generated by Django 2.2.10 on 2020-03-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_candidate_cv_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.FileField(upload_to='')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='cv_template',
        ),
    ]
