# Generated by Django 2.2.10 on 2020-03-22 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20200322_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.CVTemplate'),
        ),
    ]
