# Generated by Django 2.2.10 on 2020-03-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_auto_20200323_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvtemplate',
            name='template',
            field=models.FileField(upload_to='CV_TEMPLATES'),
        ),
    ]
