# Generated by Django 2.2.10 on 2020-03-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_auto_20200325_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_previous_position',
            field=models.TextField(blank=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='notice_period',
            field=models.TextField(blank=True),
        ),
    ]
