# Generated by Django 2.2.10 on 2020-03-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_auto_20200326_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='agreement_terms',
        ),
        migrations.AddField(
            model_name='client',
            name='agreement_term',
            field=models.DecimalField(blank=True, decimal_places=5, default=1.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='agreement_fee',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=11),
        ),
    ]
