# Generated by Django 2.2.10 on 2020-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_auto_20200330_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='point_of_contacts',
            field=models.TextField(blank=True),
        ),
    ]
