# Generated by Django 2.2.10 on 2020-04-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_client_point_of_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='point_of_contacts',
            field=models.TextField(blank=True),
        ),
    ]
