# Generated by Django 2.2.10 on 2020-04-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_client_business_development_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('edit_client_agreement_fields', 'Can edit client agreement fields'),)},
        ),
    ]
