# Generated by Django 2.2.10 on 2020-04-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0029_historicalcandidate_historicalclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.CVTemplate'),
        ),
    ]
