# Generated by Django 2.2.10 on 2020-04-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0030_auto_20200407_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_previous_salary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='current_previous_salary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
