# Generated by Django 2.2.10 on 2020-04-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0034_auto_20200410_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='signed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='signed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
