# Generated by Django 2.2.10 on 2020-04-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0035_auto_20200411_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',), 'permissions': (('edit_client_agreement_fields', 'Can edit client agreement fields'),)},
        ),
    ]
