# Generated by Django 2.2.10 on 2020-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0036_auto_20200411_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='languages',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
