# Generated by Django 2.2.10 on 2020-04-13 13:26

from django.db import migrations
from django.db.models.functions import Concat
from django.db.models import F, Value


def merge_salary_and_benefits(apps, schema_editor):
    Candidate = apps.get_model("contacts", "Candidate")
    db_alias = schema_editor.connection.alias

    # merge current previous salary
    q = Candidate.objects.using(db_alias).filter(
        current_previous_benefits__isnull=False)
    q = q.exclude(current_previous_benefits__exact='')
    q.update(
        current_previous_salary=Concat(
            F('current_previous_salary'),
            Value(' '),
            F('current_previous_benefits')),
        current_previous_benefits=''
    )

    # merge expected salary
    q = Candidate.objects.using(db_alias).filter(
        expected_benefits__isnull=False)
    q = q.exclude(expected_benefits__exact='')
    q.update(
        expected_salary=Concat(
            F('expected_salary'),
            Value(' '),
            F('expected_benefits')),
        expected_benefits=''
    )


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0038_auto_20200413_1325'),
    ]

    operations = [
        migrations.RunPython(merge_salary_and_benefits),
    ]
