# Generated by Django 2.2.10 on 2020-04-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0039_auto_20200413_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=models.TextField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='languages',
            field=models.TextField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='nationality',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
