# Generated by Django 2.2.10 on 2020-04-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0040_auto_20200413_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_male',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='is_male',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
