# Generated by Django 2.2.10 on 2020-04-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0043_auto_20200414_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
