# Generated by Django 2.2.10 on 2020-04-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0044_auto_20200414_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='initial_approach_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='initial_approach_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
