# Generated by Django 2.2.10 on 2020-07-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0046_auto_20200430_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='subscription_validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
