# Generated by Django 2.2.10 on 2020-07-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0047_supplier_subscription_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
