# Generated by Django 2.2.10 on 2020-07-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0048_auto_20200709_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='other_online_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='other_online_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_online_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='other_online_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='other_online_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='other_online_ids',
            field=models.TextField(blank=True),
        ),
    ]
