# Generated by Django 2.2.13 on 2020-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0051_auto_20201102_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
