# Generated by Django 2.2.10 on 2020-04-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200319_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='consultant_leaderboard_dashboard_last_12_months_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='consultant_leaderboard_dashboard_this_month_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='sjpc_this_month_label',
            field=models.CharField(blank=True, default='Successful job placements per consultant this month', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='sjpi_label',
            field=models.CharField(blank=True, default='Successful job placements per industry', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='ytd_client_performance_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
