# Generated by Django 2.2.10 on 2020-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200403_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='sjpi_label',
            new_name='sjatpi_label',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='consultant_leaderboard_dashboard_last_12_months_label',
            field=models.CharField(blank=True, default='Total NFI generated per consultant last 12 months', max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='consultant_leaderboard_dashboard_this_month_label',
            field=models.CharField(blank=True, default='Total NFI generated per consultant this month', max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='ytd_client_performance_label',
            field=models.CharField(blank=True, default='YTD Client Performance', max_length=100),
        ),
    ]
