# Generated by Django 2.2.10 on 2020-04-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200403_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'permissions': [('view_dashboard_type_three', 'Can view Dashboard Type Three'), ('view_dashboard_type_two', 'Can view Dashboard Type Two'), ('view_dashboard_type_one', 'Can view Dashboard Type One')], 'verbose_name': 'Dashboard Settings', 'verbose_name_plural': 'Dashboard Settings'},
        ),
    ]
