# Generated by Django 2.2.10 on 2020-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200403_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='consultant_leaderboard_dashboard_ytd_label',
            field=models.CharField(blank=True, default='Total NFI generated per consultant YTD', max_length=100),
        ),
    ]
