# Generated by Django 2.2.10 on 2020-04-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dashboard_consultant_leaderboard_dashboard_ytd_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='sjpc_ytd_label',
            field=models.CharField(blank=True, default='Successful job placements per consultant YTD', max_length=100),
        ),
    ]
