# Generated by Django 2.2.10 on 2020-04-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_dashboard_sjpc_ytd_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='ytd_industry_performance_label',
            field=models.CharField(blank=True, default='YTD Industry Performance', max_length=100),
        ),
    ]
