# Generated by Django 2.2.10 on 2020-05-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_dashboard_ytd_industry_performance_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='sjpp_ytd_label',
            field=models.CharField(blank=True, default='Successful job placements per position YTD', max_length=100),
        ),
    ]
