# Generated by Django 2.2.10 on 2020-04-30 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_integrations', '0002_auto_20200430_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinapi',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='linkedinapi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
