# Generated by Django 2.2.10 on 2020-04-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integrations', '0003_auto_20200430_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinapi',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
