# Generated by Django 2.2.10 on 2020-03-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='job_candidate',
        ),
    ]
