# Generated by Django 2.2.10 on 2020-03-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0005_auto_20200306_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='probability',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
