# Generated by Django 2.2.10 on 2020-03-12 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20200312_0028'),
        ('salespipes', '0006_auto_20200307_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='job_status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_pipeline_status', to='jobs.Status', verbose_name='equivalent job status'),
        ),
    ]
