# Generated by Django 2.2.10 on 2020-03-12 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0007_status_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
