# Generated by Django 2.2.10 on 2020-03-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0008_auto_20200312_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='recruitment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3),
        ),
    ]
