# Generated by Django 2.2.10 on 2020-03-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0010_auto_20200314_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='recruitment_term',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
