# Generated by Django 2.2.10 on 2020-03-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0011_auto_20200314_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='recruitment_term',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
