# Generated by Django 2.2.10 on 2020-03-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0013_auto_20200314_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='recruitment_rate',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='recruitment_term',
            field=models.DecimalField(blank=True, decimal_places=5, default=1.0, max_digits=15),
        ),
    ]
