# Generated by Django 2.2.10 on 2020-03-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20200315_0758'),
        ('salespipes', '0014_auto_20200315_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='candidate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_pipeline', to='jobs.JobCandidate'),
        ),
    ]
