# Generated by Django 2.2.10 on 2020-03-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0016_auto_20200315_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'permissions': [('view_report_pipeline_summary', 'Can view report Pipeline Summary'), ('view_report_pipeline_details', 'Can view report Pipeline Details')]},
        ),
    ]
