# Generated by Django 2.2.10 on 2020-03-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0017_auto_20200315_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['-date', '-job'], 'permissions': [('view_report_pipeline_summary', 'Can view report Pipeline Summary'), ('view_report_pipeline_details', 'Can view report Pipeline Details')]},
        ),
    ]
