# Generated by Django 2.2.10 on 2020-03-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20200317_0845'),
        ('salespipes', '0018_auto_20200316_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='job_candidate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipeline', to='jobs.JobCandidate'),
        ),
    ]
