# Generated by Django 2.2.10 on 2020-03-18 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0020_auto_20200317_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipeline', to='jobs.Job'),
        ),
    ]
