# Generated by Django 2.2.10 on 2020-03-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0021_auto_20200318_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['-date', '-job'], 'permissions': [('view_report_pipeline_summary', 'Can view report Pipeline Summary'), ('view_report_pipeline_details', 'Can view report Pipeline Details'), ('view_report_monthly_invoices_summary', 'Can view report Monthly Invoices Summary')]},
        ),
    ]
