# Generated by Django 2.2.10 on 2020-03-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0022_auto_20200318_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='successful_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
