# Generated by Django 2.2.10 on 2020-03-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0024_auto_20200324_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['-date', '-job'], 'permissions': [('view_report_pipeline_summary', 'Can view report Pipeline Summary'), ('view_report_pipeline_details', 'Can view report Pipeline Details'), ('view_report_monthly_invoices_summary', 'Can view report Monthly Invoices Summary'), ('view_report_successful_jobs', 'Can view report on Successful Jobs')]},
        ),
    ]
