# Generated by Django 2.2.10 on 2020-03-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0026_remove_pipeline_successful_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='should_have_invoice',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
