# Generated by Django 2.2.10 on 2020-03-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespipes', '0028_auto_20200328_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
    ]
